### ISSUE TITLE
Cannot find ice executable in newest HiCPro install directory

### ISSUE THREAD

**Issue by mblanche** [ay-lab/FitHiChIP#37]
Following the Issue #35, I also just installed HiC-Pro 2.11.4 and there is no ice executable in the scripts directory:

$ ls -lh HiC-Pro_2.11.4/scripts/
total 316K
-rwxrwxr-x 1 ubuntu ubuntu 4.7K May  9 17:14 Makefile
-rwxrwxr-x 1 ubuntu ubuntu 2.7K May  9 17:14 bowtie_combine.sh
-rwxrwxr-x 1 ubuntu ubuntu 3.3K May  9 17:14 bowtie_pairing.sh
-rwxrwxr-x 1 ubuntu ubuntu 5.3K May  9 17:14 bowtie_wrap.sh
-rwxrwxr-x 1 ubuntu ubuntu  68K May  9 17:27 build_matrix
-rwxrwxr-x 1 ubuntu ubuntu 3.2K May  9 17:14 build_raw_maps.sh
-rwxrwxr-x 1 ubuntu ubuntu  25K May  9 17:27 cutsite_trimming
-rwxrwxr-x 1 ubuntu ubuntu 7.9K May  9 17:14 hic.inc.sh
-rwxrwxr-x 1 ubuntu ubuntu 2.9K May  9 17:14 ice_norm.sh
drwxrwxr-x 2 ubuntu ubuntu 4.0K May  9 17:14 install
-rwxrwxr-x 1 ubuntu ubuntu 3.8K May  9 17:14 make_lsf_script.sh
-rwxrwxr-x 1 ubuntu ubuntu 4.6K May  9 17:14 make_plots.sh
-rwxrwxr-x 1 ubuntu ubuntu 3.6K May  9 17:14 make_sge_script.sh
-rwxrwxr-x 1 ubuntu ubuntu 3.8K May  9 17:14 make_slurm_script.sh
-rwxrwxr-x 1 ubuntu ubuntu 3.8K May  9 17:14 make_torque_script.sh
-rwxrwxr-x 1 ubuntu ubuntu  15K May  9 17:14 mapped_2hic_dnase.py
-rwxrwxr-x 1 ubuntu ubuntu  29K May  9 17:14 mapped_2hic_fragments.py
-rwxrwxr-x 1 ubuntu ubuntu 2.6K May  9 17:14 mapped_2hic_fragments.sh
-rwxrwxr-x 1 ubuntu ubuntu 2.5K May  9 17:14 mapping_stat.sh
-rwxrwxr-x 1 ubuntu ubuntu  15K May  9 17:14 markAllelicStatus.py
-rwxrwxr-x 1 ubuntu ubuntu  12K May  9 17:14 mergeSAM.py
-rwxrwxr-x 1 ubuntu ubuntu 3.6K May  9 17:14 merge_statfiles.py
-rwxrwxr-x 1 ubuntu ubuntu 3.0K May  9 17:14 merge_stats.sh
-rwxrwxr-x 1 ubuntu ubuntu 5.0K May  9 17:14 merge_valid_interactions.sh
-rwxrwxr-x 1 ubuntu ubuntu 5.3K May  9 17:14 onTarget.py
-rw-rw-r-- 1 ubuntu ubuntu 5.7K May  9 17:14 plot_hic_contacts.R
-rw-rw-r-- 1 ubuntu ubuntu 5.0K May  9 17:14 plot_hic_fragment.R
-rw-rw-r-- 1 ubuntu ubuntu 6.2K May  9 17:14 plot_mapping_portion.R
-rw-rw-r-- 1 ubuntu ubuntu 5.3K May  9 17:14 plot_pairing_portion.R
-rwxrwxr-x 1 ubuntu ubuntu 6.2K May  9 17:14 split_valid_interactions.py
drwxrwxr-x 3 ubuntu ubuntu 4.0K May  9 17:14 src

Any help would be greatly appreciated

**Comment by ay-lab** [comment]
Hi @mblanche 
Thanks for your feedback. I have updated the code "FitHiChIP_HiCPro.sh" to use the installed ICE package. The code is now compatible with this new HiC-pro version. Please check and inform for any queries.

**Comment by mblanche** [comment]
Thanks @ay-lab, pull the latest changes. However, running on the test data I still get an error, posting the error portion of the log: 

 === Regression model (training data) - average distance: 272499 number of interactions: 2612  number of bias threshold satisfying interactions: 1584 
Error in as.data.frame.default(x[[i]], optional = TRUE, stringsAsFactors = stringsAsFactors) : 
  cannot coerce class ""try-error"" to a data.frame
Calls: as.data.frame ... <Anonymous> -> as.data.frame -> as.data.frame.default
In addition: Warning message:
In parallel:::mclapply(1:length(avg_int_dist), mc.cores = ncore,  :
  all scheduled cores encountered errors in user code
Execution halted
******** FINISHED calling significant interactions
ERROR !!!!!!!! FitHiChIP could not compute the statistical significance of input interactions
Check the input parameters, or check if the number of input nonzero contact locus pairs are too few !!!
If you are using peak to peak background only (UseP2PBackgrnd=1 or stringent background), check the number of nonzero peak-to-peak locus pairs (peak-to-peak) !!! In such a case, you should go for loose background (UseP2PBackgrnd=0) for modeling interaction significance!!! Specially, if the sequencing depth of your data is very low....
awk: fatal: cannot open file `/home/ubuntu/FitHiChIP/TestData/results/FitHiChIP_Peak2ALL_b5000_L20000_U2000000/P2PBckgr_0/ICE_Bias/FitHiC_BiasCorr/FitHiChIP.interactions_FitHiC.bed' for reading (No such file or directory)
----- Extracted significant interactions ---- FDR threshold lower than: 0.01
SORRY !!!!!!!! FitHiChIP could not find any statistically significant interactions
Check the input parameters, or check if the number of input nonzero contact locus pairs are too few !!!
If you are using peak to peak background only (UseP2PBackgrnd=1 or stringent background), check the number of nonzero peak-to-peak locus pairs (peak-to-peak) !!! In such a case, you should go for loose background (UseP2PBackgrnd=0) for modeling interaction significance!!! Specially, if the sequencing depth of your data is very low....
There is no significant interaction - so no WashU specific session file is created !!
Updated CurrIntType: 4

 **** Now summarizing FitHiChIP results in the HTML file *** 

***** There are one or more errors / notifications (such as zero interaction count) associated with this execution !!!
***** Please check the console to know about them !!

**Comment by mblanche** [comment]
@ay-lab, I'm attaching the full log here 
[fithichip.log](https://github.com/ay-lab/FitHiChIP/files/4611178/fithichip.log)

**Comment by ay-lab** [comment]
Hi @mblanche 
The ICE bias is generating some excessive high values, resulting this error. Should be for some bin with very low coverage. Please use coverage bias (biastype=1) instead, which we showed as a better alternative to ICE bias, and also handles such kind of exception. Meanwhile I'll check this error in detail and get back to you soon.
